# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/2ca763ad-2533-4af2-8614-8f9d4afb80e8";
      fsType = "ext4";
    };

  fileSystems."/mnt/medias" =
    { device = "senpool01/medias";
      fsType = "zfs";
    };  
    
  fileSystems."/mnt/share" =
    { device = "senpool01/share";
      fsType = "zfs";
    };

  fileSystems."/var/certs" =
    { device = "senpool01/var/certs";
      fsType = "zfs";
    };

  fileSystems."/var/db" =
    { device = "senpool01/var/db";
      fsType = "zfs";
    };

  fileSystems."/var/dkim" =
    { device = "senpool01/var/dkim";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "senpool01/var/lib";
      fsType = "zfs";
    };
  
  fileSystems."/var/lib/docker" =
    { device = "senpool01/var/lib/docker";
      fsType = "zfs";
    };

  fileSystems."/var/sieve" =
    { device = "senpool01/var/sieve";
      fsType = "zfs";
    };

  fileSystems."/var/vmail" =
    { device = "senpool01/var/vmail";
      fsType = "zfs";
    };

  fileSystems."/var/www" =
    { device = "senpool01/var/www";
      fsType = "zfs";
    };


  swapDevices = [ { device = "/var/swapfile"; } ];

  nix.maxJobs = lib.mkDefault 2;
}
