# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ata_piix" "usb_storage" "usbhid" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "i915" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  hardware.enableRedistributableFirmware = true;
  hardware.cpu.intel.updateMicrocode = true;

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/4519fb92-2e56-4210-952a-1e5e4922e4d9";
      fsType = "ext4";
    };

  fileSystems."/mnt/medias" =
    { device = "senpool01/medias";
      fsType = "zfs";
    };

  fileSystems."/mnt/share" =
    { device = "senpool01/share";
      fsType = "zfs";
    };

  fileSystems."/mnt/backups" =
    { device = "/dev/disk/by-uuid/3d4d5f8e-9cc6-44d0-a420-d2f153a02319";
      fsType = "ext4";
      options  = [ "nofail" ];
    };

  fileSystems."/mnt/secrets" =
    { device = "senpool01/secrets";
      fsType = "zfs";
      options  = [ "nofail" ];
    };


  fileSystems."/var/certs" =
    { device = "senpool01/var/certs";
      fsType = "zfs";
    };

  fileSystems."/var/db" =
    { device = "senpool01/var/db";
      fsType = "zfs";
    };

  fileSystems."/var/dkim" =
    { device = "senpool01/var/dkim";
      fsType = "zfs";
    };

  fileSystems."/var/lib" =
    { device = "senpool01/var/lib";
      fsType = "zfs";
    };

  fileSystems."/var/lib/docker" =
    { device = "senpool01/var/lib/docker";
      fsType = "zfs";
    };

  fileSystems."/var/sieve" =
    { device = "senpool01/var/sieve";
      fsType = "zfs";
    };

  fileSystems."/var/vmail" =
    { device = "senpool01/var/vmail";
      fsType = "zfs";
    };

  fileSystems."/var/www" =
    { device = "senpool01/var/www";
      fsType = "zfs";
    };


   swapDevices = [ {
     device = "/var/swapfile";
     size = 8096;
    } ];

  nix.maxJobs = lib.mkDefault 2;
}
